use_frameworks!

target 'cocoapods-playground_Example' do
  pod 'cocoapods-playground', :path => '../'

  target 'cocoapods-playground_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
