use_frameworks!

target 'PodTests_Example' do
  pod 'PodTests', :path => '../'

  target 'PodTests_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
