use_frameworks!

platform :osx, '10.10'

target 'macOS_UI' do
  pod 'macOS_UI', :path => '../'
  # pod 'macOS_UI', :path => '../Classes'

  target 'macOS_UIUITests' do
    inherit! :search_paths

    
  end
end
